{% set name = "telepath" %}
{% set version = "0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/telepath-{{ version }}.tar.gz
  sha256: 54f4b57232461bc67c54f63f437cb6d26843c189bae6b7ba8e4457f98d78e515

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - django
    - python >=3.5

test:
  imports:
    - telepath
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wagtail/telepath
  doc_url: https://wagtail.github.io/telepath/
  summary: A library for exchanging data between Python and JavaScript
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Telepath provides a mechanism for packing structured data, including Python
    objects, into a JSON-serializable format. This mechanism can be extended to
    support any Python class, by registering the class with a corresponding
    JavaScript implementation. The packed data can then be included in an HTTP
    response, and unpacked in JavaScript to obtain an equivalent data structure
    to the original. Think of it as pickle, but with the unpickling happening in
    the browser.

extra:
  recipe-maintainers:
    - thewchan
